const types = {
  TODO_ADD_TASK: "TODO_ADD_TASK",
  TODO_REMOVE_TASK: "TODO_REMOVE_TASK",
  TODO_UPDATE_TASK: "TODO_UPDATE_TASK",
  TODO_UPDATE_FILTER_STATUS: "TODO_UPDATE_FILTER_STATUS"
};

export { types };